export const LOAD_LOGINUSER = 'LOAD_LOGINUSER';
export const UNLOAD_LOGINUSER = 'UNLOAD_LOGINUSER';
export const TOGGLE_SETTINGMENU = 'TOGGLE_SETTINGMENU';
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';
export const TOGGLE_SETTINGROLE = 'TOGGLE_SETTINGROLE';
export const LOAD_PERMISSION = 'LOAD_PERMISSION';
export const TOGGLE_LOADIMAGE = 'TOGGLE_LOADIMAGE';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
